# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: overhead.proto for package 'overhead'

# require 'grpc'
# require 'overhead_pb'

module Overhead
  module Collection
    # Interface exported by the server.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'overhead.Collection'

      rpc :GetFeature, SizeRequest, SizeResponse
      rpc :GetComplexFeature, SizeRequest, ComplexResponse
      rpc :GetTopics, SizeRequest, TopicsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
