# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: overhead.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "overhead.SizeRequest" do
    optional :size, :int32, 1
  end
  add_message "overhead.SizeResponse" do
    optional :message, :string, 1
  end
  add_message "overhead.ComplexObject" do
    optional :id, :int32, 1
  end
  add_message "overhead.ComplexResponse" do
    repeated :messages, :message, 1, "overhead.ComplexObject"
    optional :time_spend, :int32, 2
  end
  add_message "overhead.Widget" do
    optional :id, :int32, 1
    optional :type, :string, 2
    optional :data, :string, 3
    optional :created_at, :int32, 4
    optional :updated_at, :int32, 5
    optional :position, :int32, 6
  end
  add_message "overhead.Topic" do
    optional :id, :int32, 1
    optional :alternative_headline, :string, 2
    optional :announce, :string, 3
    optional :content_type, :string, 4
    optional :dispatched_at, :int32, 5
    optional :headline, :string, 6
    optional :is_visible, :bool, 7
    optional :partner_related, :bool, 8
    optional :preview_token, :string, 9
    optional :published_at, :int32, 10
    repeated :widgets, :message, 11, "overhead.Widget"
  end
  add_message "overhead.TopicsResponse" do
    repeated :topics, :message, 1, "overhead.Topic"
    optional :time_spend, :int32, 2
    optional :response_bytes, :int32, 3
  end
end

module Overhead
  SizeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("overhead.SizeRequest").msgclass
  SizeResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("overhead.SizeResponse").msgclass
  ComplexObject = Google::Protobuf::DescriptorPool.generated_pool.lookup("overhead.ComplexObject").msgclass
  ComplexResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("overhead.ComplexResponse").msgclass
  Widget = Google::Protobuf::DescriptorPool.generated_pool.lookup("overhead.Widget").msgclass
  Topic = Google::Protobuf::DescriptorPool.generated_pool.lookup("overhead.Topic").msgclass
  TopicsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("overhead.TopicsResponse").msgclass
end
