# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: topicrpc.proto for package 'topicrpc'

# require 'grpc'
# require 'topicrpc_pb'

module Topicrpc
  module Collection
    # Interface exported by the server.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'topicrpc.Collection'

      # A simple RPC.
      #
      # Obtains the feature at a given position.
      #
      # A feature with an empty name is returned if there's no feature at the given
      # position.
      rpc :GetFeature, TopicRequest, TopicReply
    end

    Stub = Service.rpc_stub_class
  end
end
